version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/TunnelWork/Ulysses.Trojan"
  dependencies_vendored = false

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "sql"
enabled = true